
package ec.gob.cuerpoagentes.vista;
import ec.gob.cuerpoagentes.controlador.Controlador;
import ec.gob.cuerpoagentes.librerias.Validacion;


public class JPIngresoAgente extends javax.swing.JPanel {

    
    Controlador controlador;
    public JPIngresoAgente(Controlador controlador) {
        this.controlador=controlador;
        initComponents();

    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxCed = new javax.swing.JComboBox<>();
        txtced = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNom1 = new javax.swing.JTextField();
        txtNom2 = new javax.swing.JTextField();
        chValidar = new javax.swing.JCheckBox();
        lblValidarCed = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApe1 = new javax.swing.JTextField();
        txtApe2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxGen = new javax.swing.JComboBox<>();
        cbxEsta = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btImprimir = new javax.swing.JButton();
        btGuardarRegistro = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        btModificar = new javax.swing.JButton();
        txtProf = new javax.swing.JTextField();
        dcFenac = new com.toedter.calendar.JDateChooser();
        txtMail = new javax.swing.JTextField();
        txtFono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxCed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Pasaporte" }));
        cbxCed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCedActionPerformed(evt);
            }
        });
        add(cbxCed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, -1));

        txtced.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcedFocusLost(evt);
            }
        });
        txtced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedActionPerformed(evt);
            }
        });
        txtced.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedKeyTyped(evt);
            }
        });
        add(txtced, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 160, -1));

        jLabel2.setText("Segundo Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtNom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNom1ActionPerformed(evt);
            }
        });
        txtNom1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNom1KeyTyped(evt);
            }
        });
        add(txtNom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 170, -1));

        txtNom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNom2ActionPerformed(evt);
            }
        });
        txtNom2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNom2KeyTyped(evt);
            }
        });
        add(txtNom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 170, -1));

        chValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chValidarActionPerformed(evt);
            }
        });
        add(chValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));
        add(lblValidarCed, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 21, 123, 20));

        jLabel3.setText("Segundo Apellido:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtApe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApe1ActionPerformed(evt);
            }
        });
        txtApe1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApe1KeyTyped(evt);
            }
        });
        add(txtApe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 170, -1));

        txtApe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApe2ActionPerformed(evt);
            }
        });
        add(txtApe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 170, -1));

        jLabel5.setText("Genero:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        cbxGen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otro" }));
        add(cbxGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 138, -1));

        cbxEsta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Union de hecho", "Divorciado", "Viudo" }));
        add(cbxEsta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 138, -1));

        jLabel6.setText("Estado Civil:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel7.setText("Direccion:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txtDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirActionPerformed(evt);
            }
        });
        add(txtDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 380, 40));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 291, 588, 186));

        btImprimir.setText("Imprimir ");
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });
        add(btImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 110, -1));

        btGuardarRegistro.setText("Guardar Registro");
        btGuardarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarRegistroActionPerformed(evt);
            }
        });
        add(btGuardarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        btEliminar.setText("Eliminar");
        add(btEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        btModificar.setText("Modificar");
        add(btModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        txtProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfActionPerformed(evt);
            }
        });
        add(txtProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 180, -1));
        add(dcFenac, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 150, -1));

        txtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailActionPerformed(evt);
            }
        });
        add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 180, -1));

        txtFono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFonoActionPerformed(evt);
            }
        });
        txtFono.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFonoPropertyChange(evt);
            }
        });
        add(txtFono, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 138, -1));

        jLabel9.setText("mail:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        jLabel10.setText("Profesion:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jLabel11.setText("Fecha nacimiento");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jLabel8.setText("Telefono:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("REGISTRO DEL PERSONAL");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        jLabel12.setText("Primer Nombre:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, -1, -1));

        jLabel13.setText("Primer Apellido:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 111, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCedActionPerformed

    private void txtcedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcedFocusLost
        // TODO add your handling code here:
        lblValidarCed.setText("" + validacion.validarCedula(txtced.getText()));
        if (validacion.validarCedula(txtced.getText())) {
        }
    }//GEN-LAST:event_txtcedFocusLost

    private void txtcedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtcedActionPerformed
Validacion validacion=new Validacion();

    private void txtcedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedKeyTyped
        // TODO add your handling code here:
        validacion.validarNumeros(evt);
    }//GEN-LAST:event_txtcedKeyTyped

    private void txtNom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNom1ActionPerformed

    private void txtNom1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNom1KeyTyped
        // TODO add your handling code here:
        validacion.validarLetras(evt);
        validacion.validarMayus(evt);
        
    }//GEN-LAST:event_txtNom1KeyTyped

    private void txtNom2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNom2KeyTyped
        // TODO add your handling code here:
        validacion.validarLetras(evt);
        validacion.validarMayus(evt);
    }//GEN-LAST:event_txtNom2KeyTyped

    private void chValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chValidarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chValidarActionPerformed

    private void txtApe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApe1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApe1ActionPerformed

    private void txtDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirActionPerformed

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        // TODO add your handling code here:
        txtArea.setText(controlador.imprimir());
    }//GEN-LAST:event_btImprimirActionPerformed

    private void btGuardarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarRegistroActionPerformed
        // TODO add your handling code here:
        controlador.llenarArrayList(txtced.getText(), txtNom1.getText(), txtNom2.getText(), txtApe1.getText(), txtApe2.getText(), txtDir.getText(), txtFono.getText(), txtMail.getText(), txtProf.getText(), dcFenac.getDate());
    }//GEN-LAST:event_btGuardarRegistroActionPerformed

    private void txtProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfActionPerformed

    private void txtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailActionPerformed

    private void txtFonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFonoActionPerformed

    private void txtFonoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFonoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFonoPropertyChange

    private void txtNom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNom2ActionPerformed

    private void txtApe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApe2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApe2ActionPerformed

    private void txtApe1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApe1KeyTyped
        // TODO add your handling code here:
        validacion.validarLetras(evt);
        validacion.validarMayus(evt);
    }//GEN-LAST:event_txtApe1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btGuardarRegistro;
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btModificar;
    private javax.swing.JComboBox<String> cbxCed;
    private javax.swing.JComboBox<String> cbxEsta;
    private javax.swing.JComboBox<String> cbxGen;
    private javax.swing.JCheckBox chValidar;
    private com.toedter.calendar.JDateChooser dcFenac;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblValidarCed;
    private javax.swing.JTextField txtApe1;
    private javax.swing.JTextField txtApe2;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtFono;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNom1;
    private javax.swing.JTextField txtNom2;
    private javax.swing.JTextField txtProf;
    private javax.swing.JTextField txtced;
    // End of variables declaration//GEN-END:variables
    // Variables declaration - do not modify//GEN-BEGIN:variables

    
}
