/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.gob.agentes.vista;


import ec.gob.agentes.controlador.Controlador;

public class AplicacionConexion extends javax.swing.JFrame {

    Controlador controlador;

    public AplicacionConexion(Controlador controlador) {
        this.controlador = controlador;
        initComponents();
        
    }

    /**
     * Creates new form AplicacionConexion
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        escritorio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdProv = new javax.swing.JTextField();
        txtNomProv = new javax.swing.JTextField();
        cbRegion = new javax.swing.JComboBox<>();
        btIngresar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        btModificar = new javax.swing.JButton();
        btAsignar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btSalir = new javax.swing.JButton();
        cbCanton = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(153, 255, 153));
        escritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("id Provincia:");
        escritorio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 39, 85, -1));

        jLabel2.setText("Nombre Provincia");
        escritorio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel3.setText("Region");
        escritorio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 85, 20));
        escritorio.add(txtIdProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 36, 180, -1));
        escritorio.add(txtNomProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 180, -1));

        cbRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIERRA", "COSTA", "ORIENTE", "INSULAR" }));
        escritorio.add(cbRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 180, -1));

        btIngresar.setText("Ingresar");
        escritorio.add(btIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 80, -1));

        btConsultar.setText("Consultar");
        escritorio.add(btConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        btEliminar.setText("Eliminar");
        escritorio.add(btEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 80, -1));

        btModificar.setText("Modificar");
        escritorio.add(btModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 80, -1));

        btAsignar.setText("Asignar tabla");
        escritorio.add(btAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDatos);

        escritorio.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, 430));

        btSalir.setText("Salir");
        escritorio.add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 100, -1));

        escritorio.add(cbCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, -1));

        jLabel4.setText("Canton");
        escritorio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
    controlador.clickdatosDBB(evt);
    controlador.cargarbtCanton();

    }//GEN-LAST:event_tblDatosMouseClicked


    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AplicacionConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AplicacionConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AplicacionConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AplicacionConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AplicacionConexion().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAsignar;
    public javax.swing.JButton btConsultar;
    public javax.swing.JButton btEliminar;
    public javax.swing.JButton btIngresar;
    public javax.swing.JButton btModificar;
    public javax.swing.JButton btSalir;
    public javax.swing.JComboBox<String> cbCanton;
    public javax.swing.JComboBox<String> cbRegion;
    public javax.swing.JPanel escritorio;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable tblDatos;
    public javax.swing.JTextField txtIdProv;
    public javax.swing.JTextField txtNomProv;
    // End of variables declaration//GEN-END:variables
}
